### ISSUE TITLE
I am unable to sync my ES from mongo meteor

### ISSUE THREAD

**Issue by jovar07** [Alino/Mongo2ES#11]
Hi. I have been trying to use elasticsearch with meteor, which I confess I am a complete newbie. My elasticsearch is running, and so is meteor. I created an watchers.js and modified it as follows. However, I get an error: W20160416-02:25:35.727(5.5)? (STDERR) elasticsearch host was not set, you must set it up!!!..Could you please help me. I am not sure where I am making the mistake. I really need this feature in my app; so any suggestions would be appreciated.

if (Meteor.isServer) {

  Meteor.startup(function () {
    console.log('running watchers');

```
// simple watching of collection:
new Mongo2ES({
  collectionName: 'chemcast',
  ES: {
    host: 'http://127.0.0.1:9200',
    index: 'manufacturers',
    type: 'suggestions'
  }
});


// watching collection and copy all already existing data:
new Mongo2ES({
  collectionName: 'chemcast',
  ES: {
    host: 'http://127.0.0.1:9200',
    index: 'manufacturers',
    type: 'suggestions'
  }
}, undefined, true);


// watching collection and using transform function (transforming data before sending it to ElasticSearch):
var transform = function (doc) {
  doc.fullName = doc.firstName + " " + doc.lastName;
  return doc;
};

new Mongo2ES({
  collectionName: 'chemcast',
  ES: {
    host: 'http://127.0.0.1:9200',
    index: 'manufacturers',
    type: 'suggestions'
  }
}, transform);
```

  });

}

**Comment by Alino** [comment]
hi @jovar07 , it seems that you didn't set env variable for elastic search.
before running Mongo2ES, try this command first if you are on linux or os x system
`export elasticsearchHost="http://127.0.0.1:9200";`
check the README on this repository, it shows which env variables are required.

**Comment by jovar07** [comment]
Thanks...Yes, you are right. Now after setting the env variables, I do get my app running, and connecting to Elasticsearch. However, I get this- 
=> App running at: http://localhost:3001/
I20160418-16:09:58.253(5.5)? checking connectivity with ElasticSearch on http://127.0.0.1:9200
I20160418-16:09:58.253(5.5)? connection with ElasticSearch successfull
W20160418-16:09:58.251(5.5)? (STDERR) warning: logit host wasn't set. Logging into console only

I thought logit host was optional, so why the error. And I think this is still not indexing the documents to ES, as I cant find the index being created.

Can you suggest me what to do?

**Comment by Alino** [comment]
please just ignore the logit warning, in next version it will be displayed only if verbose mode is activated.

are you using Mongo2ES via docker, or standalone meteor application, or did you add it as a package inside your already existing meteor app? I don't recommend to run it as a package inside existing app. It should work, but I think it will generate spam for you in the console. I run it as a separate app.

Did you create replica set for your MongoDB? Your MongoDB's [OPLOG](https://docs.mongodb.org/v3.0/core/replica-set-oplog/) must be able to be tailed.
It's how Mongo2ES works, by tailing mongo oplog and transforming the changes into ES.
therefore env variable **MONGO_OPLOG_URL** must also be set
