### ISSUE TITLE
Running watchers.js (Docker install)

### ISSUE THREAD

**Issue by hugoclrd** [Alino/Mongo2ES#12]
Hello, I can't figure out how to run watchers when installed as a Docker container. Do I have to always rebuild the images every time I change the file? Thank you!

**Comment by Alino** [comment]
hello @hugocaillard, thats the way I do it now at the moment. If I want to modify the watchers, I rebuild the image, but in my case it is not such a big issue because I am not changing the watchers often.
But if someone has a better idea how to do this, we can change it. I understand that it is pain to rebuild the image if you want to change the watchers frequently :(

**Comment by hugoclrd** [comment]
I kind of found a solution:

`Dockerfile`

```
FROM kuknito/mongo2es
COPY ./transformers.js /
```

`transformers.js`

``` js
/* transformers.js */

function transform (doc) {
  if (!(doc && doc._id)) return {}

  doc.fullName = doc.firstName + " " + doc.lastName;
  return doc
}

module.exports = [
  {
    transformer: Meteor.bindEnvironment(transform),
    opts: {
      collectionName: 'bar',
      ES: {
        host: Meteor.settings.elasticsearchHost,
        index: 'foo',
        type: 'bar'
      }
    }
  }
]
```

`kuknito/mongo2es` being my local modified version with a `watcher.js`:

``` js
/* watcher.js */

if (Meteor.isServer) {
  Meteor.startup(function () {
    var transformers = Npm.require('/transformers.js')
    for (var i = 0; i < transformers.length; i++) {
      new Mongo2ES(
        transformers[i].opts,
        transformers[i].transformer(),
        true
      )
    }
  })
}
```

So I just have to relaunch my own container which is instant.
It's still a bit drafty but it works well. I'm not sure if I'd be able to simply do:

`Dockerfile`

```
FROM kuknito/mongo2es
COPY ./watchers.js /app/
COPY ./transformers.js /
```

With no need to have a custom version of `mongo2es`. It would be hyper portable.
EDIT: I didn't try it yet (enough config for today) but I'm actually pretty sure it would work!
