### ISSUE TITLE
Why is the meteor package not recommended?

### ISSUE THREAD

**Issue by leonidez** [Alino/Mongo2ES#14]
Hi, I'm exploring different options for Mongo/Elasticsearch integration and this package is very interesting. Can you explain why the meteor package integration is not supported? Thanks.

**Comment by Alino** [comment]
Hi, I recommend to run Mongo2ES as a standalone application.
If you put it into your custom meteor app, it will:
1. spam the console (which you could easily fix)
2. steal away the performance of your meteor app

**Comment by leonidez** [comment]
Ok, thanks.
