### ISSUE TITLE
improve readme so that people can understand how to use the app

### ISSUE THREAD

**Issue by Alino** [Alino/Mongo2ES#3]
## cover these topics:
- how to write watchers
- what options are available and what each option means
- how to stop watchers

**Comment by gdw2** [comment]
I (and likely others) would be interested in seeing this on atmosphere so we can use it directly with our meteor apps.

**Comment by Alino** [comment]
@gdw2 thank you for your feedback, I created an issue for this https://github.com/Alino/Mongo2ES/issues/5
